# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'audio.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(918, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_version = QtWidgets.QLabel(self.centralwidget)
        self.lbl_version.setGeometry(QtCore.QRect(380, 300, 121, 21))
        self.lbl_version.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_version.setObjectName("lbl_version")
        self.lbl_url = QtWidgets.QLabel(self.centralwidget)
        self.lbl_url.setGeometry(QtCore.QRect(20, 300, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_url.setFont(font)
        self.lbl_url.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_url.setObjectName("lbl_url")
        self.txt_url = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_url.setGeometry(QtCore.QRect(220, 330, 531, 31))
        self.txt_url.setObjectName("txt_url")
        self.btn_descargar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_descargar.setEnabled(True)
        self.btn_descargar.setGeometry(QtCore.QRect(340, 440, 91, 31))
        self.btn_descargar.setObjectName("btn_descargar")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(280, 480, 371, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.lbl_status = QtWidgets.QLabel(self.centralwidget)
        self.lbl_status.setGeometry(QtCore.QRect(310, 600, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_status.setFont(font)
        self.lbl_status.setText("")
        self.lbl_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_status.setObjectName("lbl_status")
        self.btn_destino = QtWidgets.QPushButton(self.centralwidget)
        self.btn_destino.setGeometry(QtCore.QRect(110, 400, 91, 31))
        self.btn_destino.setObjectName("btn_destino")
        self.txt_ruta = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_ruta.setGeometry(QtCore.QRect(220, 400, 281, 33))
        self.txt_ruta.setObjectName("txt_ruta")
        self.lbl_titulo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_titulo.setGeometry(QtCore.QRect(20, 0, 861, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_titulo.sizePolicy().hasHeightForWidth())
        self.lbl_titulo.setSizePolicy(sizePolicy)
        self.lbl_titulo.setText("")
        self.lbl_titulo.setPixmap(QtGui.QPixmap(":/logo_cabeza/logosoftware.png"))
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 520, 791, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 370, 391, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(540, 370, 271, 61))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 30, 125, 29))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(140, 30, 125, 29))
        self.radioButton_2.setObjectName("radioButton_2")
        self.btn_cancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancelar.setEnabled(False)
        self.btn_cancelar.setGeometry(QtCore.QRect(440, 440, 91, 31))
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.lbl_titulo.raise_()
        self.lbl_version.raise_()
        self.lbl_url.raise_()
        self.txt_url.raise_()
        self.btn_descargar.raise_()
        self.lbl_status.raise_()
        self.btn_destino.raise_()
        self.txt_ruta.raise_()
        self.progressBar.raise_()
        self.tableWidget.raise_()
        self.label.raise_()
        self.groupBox.raise_()
        self.btn_cancelar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAcerca_de = QtWidgets.QAction(MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Download Audio From Youtube"))
        self.lbl_version.setText(_translate("MainWindow", "Versión 0.5 Alpha"))
        self.lbl_url.setText(_translate("MainWindow", "Ingrese URL de Youtube:"))
        self.btn_descargar.setText(_translate("MainWindow", "Descargar"))
        self.btn_destino.setText(_translate("MainWindow", "Destino:"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre "))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Duración"))
        self.label.setText(_translate("MainWindow", "Seleccione la ruta de salida o dejela por defecto:"))
        self.groupBox.setTitle(_translate("MainWindow", "Seleccione  un Formato:"))
        self.radioButton.setText(_translate("MainWindow", "MP3"))
        self.radioButton_2.setText(_translate("MainWindow", "OGG"))
        self.btn_cancelar.setText(_translate("MainWindow", "Cancelar"))
        self.actionAcerca_de.setText(_translate("MainWindow", "Acerca de"))


import loco_cabeza_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
