# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'audio.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(918, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_version = QtWidgets.QLabel(self.centralwidget)
        self.lbl_version.setGeometry(QtCore.QRect(380, 210, 121, 21))
        self.lbl_version.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_version.setObjectName("lbl_version")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(40, 230, 841, 451))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lbl_url = QtWidgets.QLabel(self.tab)
        self.lbl_url.setGeometry(QtCore.QRect(10, 10, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_url.setFont(font)
        self.lbl_url.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_url.setObjectName("lbl_url")
        self.txt_url = QtWidgets.QLineEdit(self.tab)
        self.txt_url.setGeometry(QtCore.QRect(150, 40, 531, 31))
        self.txt_url.setObjectName("txt_url")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 80, 391, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_ruta = QtWidgets.QLineEdit(self.tab)
        self.txt_ruta.setGeometry(QtCore.QRect(150, 120, 281, 33))
        self.txt_ruta.setObjectName("txt_ruta")
        self.btn_destino = QtWidgets.QPushButton(self.tab)
        self.btn_destino.setGeometry(QtCore.QRect(40, 120, 91, 31))
        self.btn_destino.setObjectName("btn_destino")
        self.btn_descargar = QtWidgets.QPushButton(self.tab)
        self.btn_descargar.setEnabled(True)
        self.btn_descargar.setGeometry(QtCore.QRect(290, 170, 91, 31))
        self.btn_descargar.setObjectName("btn_descargar")
        self.btn_cancelar = QtWidgets.QPushButton(self.tab)
        self.btn_cancelar.setEnabled(False)
        self.btn_cancelar.setGeometry(QtCore.QRect(410, 170, 91, 31))
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(490, 100, 271, 61))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 30, 125, 29))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(140, 30, 125, 29))
        self.radioButton_2.setObjectName("radioButton_2")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(210, 210, 371, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(20, 260, 791, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.lbl_status = QtWidgets.QLabel(self.tab)
        self.lbl_status.setGeometry(QtCore.QRect(260, 350, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_status.setFont(font)
        self.lbl_status.setText("")
        self.lbl_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_status.setObjectName("lbl_status")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lbl_url_2 = QtWidgets.QLabel(self.tab_2)
        self.lbl_url_2.setGeometry(QtCore.QRect(20, 10, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_url_2.setFont(font)
        self.lbl_url_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_url_2.setObjectName("lbl_url_2")
        self.txt_url_2 = QtWidgets.QLineEdit(self.tab_2)
        self.txt_url_2.setGeometry(QtCore.QRect(170, 40, 531, 31))
        self.txt_url_2.setObjectName("txt_url_2")
        self.tabla_datos = QtWidgets.QTableWidget(self.tab_2)
        self.tabla_datos.setGeometry(QtCore.QRect(0, 130, 841, 291))
        self.tabla_datos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_datos.setColumnCount(5)
        self.tabla_datos.setObjectName("tabla_datos")
        self.tabla_datos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_datos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_datos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_datos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_datos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_datos.setHorizontalHeaderItem(4, item)
        self.btn_datos = QtWidgets.QPushButton(self.tab_2)
        self.btn_datos.setGeometry(QtCore.QRect(240, 80, 101, 29))
        self.btn_datos.setObjectName("btn_datos")
        self.btn_exportar = QtWidgets.QPushButton(self.tab_2)
        self.btn_exportar.setGeometry(QtCore.QRect(370, 80, 101, 31))
        self.btn_exportar.setObjectName("btn_exportar")
        self.btn_nuevo = QtWidgets.QPushButton(self.tab_2)
        self.btn_nuevo.setGeometry(QtCore.QRect(490, 80, 101, 29))
        self.btn_nuevo.setObjectName("btn_nuevo")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 20, 901, 181))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAcerca_de = QtWidgets.QAction(MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Download Audio From Youtube"))
        self.lbl_version.setText(_translate("MainWindow", "Versión 0.6 Alpha"))
        self.lbl_url.setText(_translate("MainWindow", "Ingrese URL de Youtube:"))
        self.label.setText(_translate("MainWindow", "Seleccione la ruta de salida o dejela por defecto:"))
        self.btn_destino.setText(_translate("MainWindow", "Destino:"))
        self.btn_descargar.setText(_translate("MainWindow", "Descargar"))
        self.btn_cancelar.setText(_translate("MainWindow", "Cancelar"))
        self.groupBox.setTitle(_translate("MainWindow", "Seleccione  un Formato:"))
        self.radioButton.setText(_translate("MainWindow", "MP3"))
        self.radioButton_2.setText(_translate("MainWindow", "OGG"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre "))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Duración"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Descargar Audio"))
        self.lbl_url_2.setText(_translate("MainWindow", "Ingrese URL de Youtube:"))
        item = self.tabla_datos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Titulo"))
        item = self.tabla_datos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Duracion"))
        item = self.tabla_datos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Visitas"))
        item = self.tabla_datos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Autor"))
        item = self.tabla_datos.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Imagen"))
        self.btn_datos.setText(_translate("MainWindow", "Obtener"))
        self.btn_exportar.setText(_translate("MainWindow", "Exportar"))
        self.btn_nuevo.setText(_translate("MainWindow", "Nuevo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Obtener Metadatos"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/logo_software/logosoftware.png\"/></p></body></html>"))
        self.actionAcerca_de.setText(_translate("MainWindow", "Acerca de"))


import logosoftware_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
